In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('KMeansDataset.csv')

In [3]:
data

Feature1  Feature2
0   1.149014  1.958521
1   1.194307  2.456909
2   0.929754  1.929759
3   1.473764  2.230230
4   0.859158  2.162768
..       ...       ...
95  8.866046  2.256920
96  9.064228  1.626278
97  9.051954  2.115595
98  8.734843  2.046118
99  9.017463  1.657109

[100 rows x 2 columns]

In [8]:
df = data.iloc[np.random.permutation(len(data))].reset_index(drop=True)
k=3

In [14]:
c1 = df.iloc[0].values

In [16]:
c1[0]

np.float64(1.0725886814698102)

In [17]:
dist = [(df.iloc[i].values[0] - c1[0])**2 + (df.iloc[i].values[1] - c1[1])**2 for i in range(1,len(data))]

In [19]:
tot_dist = np.sum(dist)

In [20]:
tot_dist

np.float64(4229.233998948601)

In [21]:
prob = dist/tot_dist

In [22]:
prob

array([1.73764369e-05, 1.39256763e-02, 4.96281368e-05, 1.73745480e-02,
       1.69660172e-05, 6.84289900e-05, 4.98416425e-05, 3.34836400e-05,
       1.21166594e-04, 1.63125127e-02, 1.39116546e-04, 5.80317542e-05,
       1.60777522e-02, 1.52863603e-02, 1.55951221e-02, 1.52788253e-04,
       1.45332080e-02, 2.34410653e-04, 1.37309494e-02, 1.49474424e-02,
       1.44522056e-02, 1.53076821e-02, 6.91091804e-08, 1.46391694e-02,
       1.31417519e-02, 1.45247036e-02, 1.52214166e-02, 9.33010588e-05,
       3.16891587e-04, 1.50110996e-02, 1.46133089e-02, 1.90980793e-04,
       1.47560267e-02, 1.37019984e-02, 7.45818699e-05, 1.50201017e-02,
       1.39097222e-04, 1.53639605e-04, 1.57658280e-02, 5.72637348e-06,
       1.38099163e-02, 1.41197827e-02, 1.52511133e-02, 7.96310899e-05,
       1.50167088e-02, 1.98268650e-04, 1.39729000e-02, 1.57983164e-02,
       1.71530957e-02, 9.24652168e-05, 6.48246813e-05, 1.65681391e-02,
       1.39014614e-02, 1.35082840e-02, 1.53320242e-02, 9.77256970e-05,
      

In [24]:
c2 = df.iloc[np.argmax(prob)].values

In [25]:
c2

array([0.66809951, 1.64113801])

In [26]:
dist = [(df.iloc[i].values[0] - c2[0])**2 + (df.iloc[i].values[1] - c2[1])**2 for i in range(1,len(data))]

In [27]:
tot_dist = np.sum(dist)

In [28]:
prob = dist/tot_dist

In [29]:
c3 = df.iloc[np.argmax(prob)].values

In [30]:
c3

array([9.24405517, 1.63074071])